#setwd("C:/Users/mosu001/OneDrive - The University of Auckland/Documents/uoa/industry-engagement/PracWork")
setwd("C:/Data/PracWork")


library(dplyr)
library(tidyverse)
library(ggplot2)
raw_df <- read.csv("C:/Data/PracWork/practical_work_registration report 29-03-2023.csv")
sort_df <- raw_df[order(raw_df$Company.Name),]

invalid = c(
  "",
  "...",
  "5b Kindergarten Dr, Conifer Grove","#NAME?"
)

valid_df = sort_df[!(sort_df$Company.Name %in% invalid),]

needsChange = c(
  " (aerospace New Business Networks Company Limited)",
  "(fujian Liansheng Paper Industry Co., Ltd.)",
  "9spokes International Limited", "2022 Nz Robot Olympiad","9 Spokes","9 Spokes International","9spokes International","9spokes International Limited",
  "Abb Napier","Abb Nz Ltd", "Abb Ltd","Acciona Construction", "Accord Precision Machining","Ach Conuslting Ltd","Ach Consulting Engineers",
  "Active Engineering","Advanced Aerospace Ltd","Advanced Aerospace","Advanced Personal","Advanced Personnel Services Ltd","Aecom Nz",
  "Aecom Ltd","Aecom New Zealand Limited","Aecom New Zealand","Aeroqual Ltd","Air Liquide New Zealand Limited","Air Liquide New Zealand",
  "Air New Zealand Engineering Services","Airlab","Alchemy Systems Ltd","Alimetry Ltd.","Amazon Web Services New Zealand Limited","Amazon Web Services Nzl Ltd",
  "Amphenol Phitek Limited - Auckland, New Zealand","Apollo Living - Commercial  Residential","Apple New Zealand","Apple","Apple Technology Services (apple)",
  "Ar  Associated Ltd", "Aroa Biosurgery","Aroa Biosurgery Ltd","Aroa","Arup","Arup New Zealand", "Asb","Asb Bank","Asbuilt Digital","Asbuilt Ltd",
  "Asona Limited", "Aspec", "Atlassian Corporation Plc", "Auckland Bioengineering Institute","Auckland Bioengineering Institute - Empathic Computing Laboratory",
  "Auckland Bioengineering Institute, The University Of Auckland", "Auckland Bioengineering Institute (abi)", "Auckland Bio Engineering Institute",
  "Auckland Bioengineering Institute, University Of Auckland", "Auckland Bioengineering Institute - Implantable Devices Group",
  "Auckland Biomedical Engineering", "Auckland Space Institute - Te Pnaha tea","Auckland Uniservices Limited", "Auckland University",
  "Auckland University Maker Space", "Aurecon, Tauranga","Aurecon, New Zealand", "Aurecon Nz", "Aurecon New Zealand", "Aurecon New Zealand Limited",
  "Aurecon Group Ltd. - Auckland, New Zealand", "Aurecon New Zealand Ltd","Aurecon Group Ltd.", "Aurecon Group", "Aut School Of Science Research",
  "Aut Internship", "Aviat Networks Nz", "Awa Environmental", "Babbage Consultants Ltd.", "Babbage", "Babbage Consultants Ltd", "Babcock Australasia",
  "Babcock (nz) Ltd", "Babcock Australia  New Zealand", "Babcock Nz Ltd","Babcock International","Babcock International Nz", "Babcock Nz",
  "Babcock New Zealand", "Babcock Nz Ltd.", "Ballance-agri Nutrients", "Bank Of New Zealand - Wellington, New Zealand", "Bartley Consultants",
  "Bay Of Plenty Regional Council And Rotorua Lakes Council", "Bcd Group Limited", "Bc Group Nz", "Beca Wellington", "Beca - Wellington, New Zealand",
  "Beca Ltd", "Beca Limited", "Beca Group Ltd", "Beca Group Limited", "Beca Group", "Beca Ltd.", "Beca Group Limited.", "Beca Applied Technologies",
  "Biolumic Ltd", "Bison Group Limited", "Blue Barn Consulting Ltd.", "Blue Cars Ltd", "Bluelab Corporation", "Bricks4kidz", "Bricks 4 Kidz New Zealand",
  "Broad Solutions Limited", "Bsk Consulting Consultant Engineers", "Buckley Systems Limited", "Buckley Systems Ltd","Burohappold", "Calibre Consulting Limited",
  "Calibre Group New Zealand","Cares, University Of Auckland","Cares","Carrel Electrade Limited", "Cb Civil And Drainage Ltd","Cb Civil",
  "Cemix Products Ltd","Centre For Advanced Composite Materials - The University Of Auckland", "Chester Consultants Ltd.", "Chester Consultants",
  "China Construction Third Engineering Bureau Co.ltd", "Chorus New Zealand", "Cirrus Materials Science Ltd", "Cirrus Materials Science Limited",
  "City Care Ltd.", "Civil Plan", "Civilplan","Ckl","Claymark Profiles Ltd.", "Cll Service  Solutions","Cloudstore Limited", "Cnc Machining Co. Ltd",
  "Coca-cola Amatil", "Cognex", "Compac", "Compac Sorting Limited","Compac Sorting","Compac Sorting Equipment Ltd","Compliance Audit Systems Ltd",
  "Comprehensive Care Limited", "Contact Energy Ltd", "Contact Energy Limited","Coretex Nz Limited", "Cornerstone Engineering Consultants Ltd",
  "Cornerstone Engineering Consultants","Cornerstone Engineering Consultant", "Cosmos Building Limited", "Covertex", "Cpb Contractorws", "Crossfire, A Jensen Hughes Company",
  "Crossfire Fire Engineering", "Crown Equipment Corporation", "Crown Equipment", "Crown Equipment - Rtc", "Crown Rtc", "Crown Robotic Technology Centre",
  "Cse Consaultants Ltd", "Cse Consultants Limited", "Cubic Defense Nz","Cubic Defense New Zealand", "Daifuku Oceania Trading As Bcs New Zealand", "Daifuku",
  "Daikin New Zealand", "Datacom Group Ltd.", "Datacom Group Limited", "Datacom Group Ltd", "Datacom Ltd", "Datamars Tru-test Ltd",
  "Datamars Ltd", "Datamars New Zealand", "Datamars (tru-test)", "Datamars Limited", "Db Breweries Ltd Waitemata", "Db Breweries  Heineken",
  "Deloitte New Zealand", "Dempsey Wood Civil Limited", "Dempsey Wood Civil", "Dempsey Wood Civil Ltd.", "Department Of Engineering Science, The University Of Auckland",
  "Department Of Engineering Science, University Of Auckland", "Department Of Engineering Science", "Department Of Mechanical Engineering At The University Of Auckland",
  "Department Of Exercise Science", "Department Of Mathematics, The University Of Auckland", "Department Of Civil And Environmental Engineering, Faculty Of Engineering, University Of Auckland",
  "Department Of Chemical  Materials Engineering, University Of Auckland", "Design Production Ltd", "Developed", "Dhc Consulting Group Ltd",
  "Digital Sensing Limited  Manufacturing Systems Limited", "Direct Control Ltd", "Dn3010", "Dodd Civil Consultants Ltd", "Douglas Pharmaceuticals Ltd",
  "Downer Northern Region Depot", "Downer Nz", "Downer New Zealand", "Downer Nz Ltd", "Downer Nz (gisborne)", "Downer Group", "Downer New Zealand Limited", 
  "Downer Group Nz", "Downer Utilities Alliance New Zealand Limited", "Downer Nz Limted", "Downer Newzealand", "Downer Nz - Link Alliance",
  "Dreamcast Civil Ltd",  "Eaton Electrical Equipment Co., Ltd.", "Ecubed Building Workshop Ltd", "Eg Whiter Ltd", "Eighty6 Engineering", "Elite Mountain Home Limited",
  "Energy Solution Providers", "Engeo Limited", "Engex","Engineering Design Consultant",  "Engineering Design Consultants Ltd", "Engineering Science Department, The University Of Auckland", 
  "Engineous Consulting Ltd", "Ergo Consulting","Ernst  Young Limited",  "Ernst  Young (ey)", "Ernst And Young", "Ernst  Young New Zealand", "Ernst And Young Global Limited",
  "Eroad Ltd", "Etel", "Etel Limited","Ey - Ernst And Young", "Ey", "Eze Business Solutions", ""
 
  )
change <- c(
  " (aerospace New Business Networks Company Limited)"="Aerospace New Business Networks Company Limited",
  "(fujian Liansheng Paper Industry Co., Ltd.)"="Fujian Liansheng Paper Industry Co., Ltd.",
  "9spokes International Limited"="9 Spokes International Limited",
  "2022 Nz Robot Olympiad" = "2022 Nz Robotics Olympiad",
  "22 Degrees Building Services Engineering"= "22 Degrees Ltd",
  "9 Spokes"="9 Spokes International Limited",
  "9 Spokes International"="9 Spokes International Limited",
  "9spokes International"="9 Spokes International Limited",
  "9spokes International Limited"="9 Spokes International Limited",
  "Abb Napier"="Abb",
  "Abb Nz Ltd"="Abb",
  "Abb Ltd"="Abb",
  "Acciona Construction"="Acciona",
  "Accord Precision Machining"="Accord Precision Cnc Machining",
  "Ach Consulting Engineers"="Ach Consulting Ltd",
  "Ach Conuslting Ltd"="Ach Consulting Ltd",
  "Active Engineering"="Active Engineering Limited",
  "Advanced Aerospace Ltd"="Advanced Aerospace Limited",
  "Advanced Aerospace"="Advanced Aerospace Limited",
  "Advanced Personal"="Advanced Personnel",
  "Advanced Personnel Services Ltd"="Advanced Personnel",
  "Aecom Nz"="Aecom",
  "Aecom Ltd"="Aecom",
  "Aecom New Zealand Limited"="Aecom",
  "Aecom New Zealand"="Aecom",
  "Aeroqual Ltd"="Aeroqual",
  "Air Liquide New Zealand"="Air Liquide",
  "Air Liquide New Zealand Limited"="Air Liquide",
  "Air New Zealand Engineering Services"="Air New Zealand",
  "Airlab"="Airlab Ltd",
  "Alchemy Systems Ltd"="Alchemy Systems Limited",
  "Alimetry Ltd."="Alimetry",
  "Amazon Web Services New Zealand Limited"="Amazon Web Services",
  "Amazon Web Services Nzl Ltd"="Amazon Web Services",
  "Amphenol Phitek Limited - Auckland, New Zealand"="Amphenol Phitek Limited",
  "Apollo Living - Commercial  Residential"="Apolloliving Limited",
  "Apple"="Apple Inc.",
  "Apple New Zealand"="Apple Inc.",
  "Apple Technology Services (apple)"="Apple Inc.",
  "Ar  Associated Ltd"="Ar  Associates Ltd",
  "Aroa Biosurgery"="Aroa Biosurgery Limited",
  "Aroa Biosurgery Ltd"="Aroa Biosurgery Limited",
  "Aroa"="Aroa Biosurgery Limited",
  "Arup"="Arup New Zealand Limited",
  "Arup New Zealand"="Arup New Zealand Limited",
  "Asb"="Asb Bank Limited",
  "Asb Bank"="Asb Bank Limited",
  "Asbuilt Ltd"="Asbuilt",
  "Asbuilt Digital"="Asbuilt",
  "Asona Limited"="Asona",
  "Aspec"="Aspec Construction",
  "Atlassian Corporation Plc"="Atlassian",
  "Auckland Bioengineering Institute"="The University of Auckland",
  "Auckland Bioengineering Institute - Empathic Computing Laboratory"="The University of Auckland",
  "Auckland Biomedical Engineering"="The University of Auckland",
  "Auckland Bioengineering Institute, The University Of Auckland"="The University of Auckland",
  "Auckland Bioengineering Institute (abi)"="The University of Auckland",
  "Auckland Bio Engineering Institute"="The University of Auckland",
  "Auckland Bioengineering Institute, University Of Auckland"="The University of Auckland",
  "Auckland Bioengineering Institute - Implantable Devices Group"="The University of Auckland",
  "Auckland Space Institute - Te Pnaha tea"="The University of Auckland",
  "Auckland Uniservices Limited"="The University of Auckland",
  "Auckland University"="The University of Auckland",
  "Auckland University Maker Space"="The University of Auckland",
  "Aurecon, Tauranga"="Aurecon Group Ltd",
  "Aurecon, New Zealand"="Aurecon Group Ltd",
  "Aurecon Nz"="Aurecon Group Ltd",
  "Aurecon New Zealand"="Aurecon Group Ltd",
  "Aurecon New Zealand Limited"="Aurecon Group Ltd",
  "Aurecon Group Ltd."="Aurecon Group Ltd",
  "Aurecon Group Ltd. - Auckland, New Zealand"="Aurecon Group Ltd",
  "Aurecon New Zealand Ltd"="Aurecon Group Ltd",
  "Aurecon Group"="Aurecon Group Ltd",
  "Aut School Of Science Research"="Aut",
  "Aut Internship"="Aut",
  "Aviat Networks Nz"="Aviat Networks",
  "Awa Environmental"="Awa Environmental Ltd",
  "Babbage Consultants Ltd." = "Babbage Consultants",
  "Babbage" = "Babbage Consultants", 
  "Babbage Consultants Ltd" = "Babbage Consultants", 
  "Babcock Australasia" = "Babcock",
  "Babcock (nz) Ltd" = "Babcock",
  "Babcock Australia  New Zealand" = "Babcock",
  "Babcock Nz Ltd" = "Babcock",
  "Babcock International" = "Babcock",
  "Babcock International Nz" = "Babcock",
  "Babcock Nz" = "Babcock",
  "Babcock New Zealand" = "Babcock",
  "Babcock Nz Ltd." = "Babcock",
  "Ballance-agri Nutrients" = "Ballance Agri-nutrients",
  "Bank Of New Zealand - Wellington, New Zealand" = "Bank Of New Zealand",
  "Bartley Consultants" = "Bartley Consultants Limited",
  "Bay Of Plenty Regional Council And Rotorua Lakes Council" = "Bay Of Plenty Regional Council",
  "Bc Group Nz" = "Bcd Group",
  "Bcd Group Limited" = "Bcd Group",
  "Beca Wellington" = "Beca",
  "Beca - Wellington, New Zealand" = "Beca",
  "Beca Ltd" = "Beca",
  "Beca Limited" = "Beca",
  "Beca Group Ltd" = "Beca",
  "Beca Group Limited" = "Beca",
  "Beca Group" = "Beca",
  "Beca Ltd." = "Beca",
  "Beca Group Limited." = "Beca",
  "Beca Applied Technologies" = "Beca",
  "Biolumic Ltd" = "Biolumic",
  "Bison Group Limited" = "Bison Group",
  "Blue Barn Consulting Ltd."="Blue Barn",
  "Blue Cars Ltd" ="Blue Cars",
  "Bluelab Corporation" = "Bluelab",
  "Bricks 4 Kidz New Zealand"="Bricks 4 Kidz",
  "Bricks4kidz"="Bricks 4 Kidz",
  "Broad Solutions Limited" = "Broad Solutions",
  "Bsk Consulting Consultant Engineers" = "Bsk Consulting Engineers",
  "Buckley Systems Ltd" = "Buckley Systems",
  "Buckley Systems Limited" = "Buckley Systems",
  "Bunnings Warehouse Ltd" = "Bunnings Warehouse",
  "Burohappold" = "Burohapp",
  "Calibre Consulting Limited" = "Calibre Consulting",
  "Calibre Group New Zealand" = "Calibre Consulting",
  "Cares" = "Cares University Of Auckland",
  "Cares, University Of Auckland" = "Cares University Of Auckland",
  "Carrel Electrade Limited" = "Carrel Electrade Ltd",
  "Cb Civil" = "Cb Civil  Drainage",
  "Cb Civil And Drainage Ltd" = "Cb Civil  Drainage",
  "Cemix Products Ltd"="Cemix",
  "Centre For Advanced Composite Materials - The University Of Auckland" = "Centre For Advanced Composite Materials",
  "Chester Consultants Ltd."="Chester Consultants Ltd",
  "Chester Consultants"="Chester Consultants Ltd",
  "China Construction Third Engineering Bureau Co.ltd" = "China Construction Third Engineering Bureau Group Co.,ltd",
  "Chorus New Zealand"="Chorus",
  "Cirrus Materials Science Ltd" = "Cirrus Materials Science",
  "Cirrus Materials Science Limited" ="Cirrus Materials Science", 
  "City Care Ltd." = "City Care Goup",
  "City Rail Link Limited" = "City Rail Link",
  "City Rail Linkconnectus Jv" = "City Rail Link",
  "Civil Plan" = "Civilplan Consultants Limited",
  "Civilplan" = "Civilplan Consultants Limited",
  "Ckl" = "Ckr Homes",
  "Claymark Profiles Ltd." = "Claymark Group Limited Partnership",
  "Cll Service  Solutions" = "Cll Services And Solutions",
  "Cloudstore Limited" = "Cloudstore",
  "Cnc Machining Co. Ltd" = "Cnc Machining Co Ltd",
  "Coca-cola Amatil" = "Coca Cola Amatil",
  "Cognex" = "Cognex Corporation",
  "Compac Sorting Limited" = "Compac Sorting Equipment",
  "Compac" = "Compac Sorting Equipment",
  "Compac Sorting" = "Compac Sorting Equipment",
  "Compac Sorting Equipment Ltd" = "Compac Sorting Equipment",
  "Compliance Audit Systems Ltd" = "Compliance Audit Systems",
  "Comprehensive Care Limited" = "Comprehensive Care Ltd",
  "Contact Energy Limited" = "Contact Energy",
  "Contact Energy Ltd" = "Contact Energy",
  "Coretex Nz Limited" = "Coretex",
  "Cornerstone Engineering Consultants Ltd" = "Cornerstone Engineering Consultants Limited",
  "Cornerstone Engineering Consultants" = "Cornerstone Engineering Consultants Limited",
  "Cornerstone Engineering Consultant" = "Cornerstone Engineering Consultants Limited",
  "Cosmos Building Limited" = "Cosmos Building Ltd",
  "Covertex" = "Covertex Ltd",
  "Cpb Contractorws" = "Cpb Contractors",
  "Crossfire, A Jensen Hughes Company" = "Crossfire",
  "Crossfire Fire Engineering" = "Crossfire",
  "Crown Equipment Corporation" = "Crown Equipment Limited",
  "Crown Equipment - Rtc" = "Crown Equipment Limited",
  "Crown Equipment" = "Crown Equipment Limited",
  "Crown Rtc" = "Crown Equipment Limited",
  "Crown Robotic Technology Centre" = "Crown Equipment Limited",
  "Cse Consultants Limited" = "Cse Consultants Ltd",
  "Cse Consaultants Ltd" = "Cse Consultants Ltd",
  "Cubic Defense Nz" = "Cubic Defence New Zealand",
  "Cubic Defense New Zealand" = "Cubic Defence New Zealand",
  "Daifuku" = "Daifuku Oceania",
  "Daifuku Oceania Trading As Bcs New Zealand" = "Daifuku Oceania",
  "Daikin New Zealand" = "Daikin Air Conditioning Nz Ltd",
  "Datacom Ltd" = "Datacom",
  "Datacom Group Ltd" = "Datacom",
  "Datacom Group Limited" = "Datacom",
  "Datacom Group Ltd." = "Datacom",
  "Datamars Tru-test Ltd" = "Datamars",
  "Datamars Ltd" = "Datamars",
  "Datamars New Zealand" = "Datamars",
  "Datamars (tru-test)" = "Datamars",
  "Datamars Limited" = "Datamars",
  "Db Breweries  Heineken" = "Db Breweries",
  "Db Breweries Ltd Waitemata" = "Db Breweries",
  "Deloitte New Zealand" = "Deloitte",
  "Dempsey Wood Civil Ltd." = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil Limited" = "Dempsey Wood",
  
  "Department Of Engineering Science, The University Of Auckland" = "The University Of Auckland",
  "Department Of Engineering Science, University Of Auckland" = "The University Of Auckland",
  "Department Of Engineering Science" = "The University Of Auckland",
  "Department Of Mechanical Engineering At The University Of Auckland" = "The University Of Auckland",
  "Datacom Group Ltd." = "The University Of Auckland",
  "Department Of Exercise Science" = "The University Of Auckland",
  "Department Of Mathematics, The University Of Auckland" = "The University Of Auckland",
  "Department Of Civil And Environmental Engineering, Faculty Of Engineering, University Of Auckland" = "The University Of Auckland",
  "Department Of Chemical  Materials Engineering, University Of Auckland" = "The University Of Auckland",
  "Design Production Ltd" = "Design Production",
  "Developed" = "Developed Consultants Ltd",
  "Dhc Consulting Group Ltd" = "Dhc Consulting Ltd",
  "Digital Sensing Limited  Manufacturing Systems Limited" = "Digital Sensing Limited",
  "Direct Control Ltd" = "Direct Control",
  "Dn3010" = "Dn 3010 Limited",
  "Dodd Civil Consultants Ltd" = "Dodd Civil Consultants",
  "Douglas Pharmaceuticals Ltd" = "Douglas Pharmaceuticals",
  "Downer New Zealand" = "Downer",
  "Downer Group Nz" = "Downer",
  "Downer Nz" = "Downer",
  "Downer Group" = "Downer",
  "Downer Nz - Link Alliance" = "Downer",
  "Downer Newzealand" = "Downer",
  "Downer Nz Ltd" = "Downer",
  "Downer Nz Limted" = "Downer",
  "Downer New Zealand Limited" = "Downer",
  "Downer Utilities Alliance New Zealand Limited" = "Downer",
  "Downer Nz (gisborne)" = "Downer",
  "Downer Northern Region Depot" = "Downer",
  "Dreamcast Civil Ltd" = "Dreamcast Group",
  "Eaton Electrical Equipment Co., Ltd." = "Eaton Electrical Equipment Co., Ltd",
  "Ecubed Building Workshop Ltd" = "Ecubed",
  "Eg Whiter Ltd" = "Eg Whiter",
  "Eighty6 Engineering" = "Eighty6 Engineering Limited",
  "Elite Mountain Home Limited" = "Elite Mountain Homes Ltd",
  "Energy Solution Providers" = "Energy Solution Providers Ltd",
  "Engeo Limited" = "Engeo",
  "Engex" = "Engex Ltd",
  "Engineering Design Consultant" = "Engineering Design Consultants",
  "Engineering Design Consultants Ltd" = "Engineering Design Consultants",
  "Engineering Science Department, The University Of Auckland" = "The University Of Auckland",
  "Engineous Consulting Ltd" = "Engineous Consulting",
  "Ergo Consulting" = "Ergo Consulting Ltd",
  "Ernst  Young Limited" = "Ernst  Young",
  "Ernst  Young (ey)" = "Ernst  Young",
  "Ernst And Young" = "Ernst  Young",
  "Ernst And Young Global Limited" = "Ernst  Young",
  "Ernst  Young New Zealand" = "Ernst  Young",
  "Eroad Ltd" = "Eroad",
  "Etel Limited" = "Etel Transformers Ltd",
  "Etel" = "Etel Transformers Ltd",
  "Ey - Ernst And Young" = "Ernst  Young",
  "Ey" = "Ernst  Young",
  "Eze Business Solutions" = "Eze Business Solutions Ltd",
  
  
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
)

change_df = valid_df
change_df$Company.Name = ifelse(
  change_df$Company.Name %in% needsChange,
  change[change_df$Company.Name],
  change_df$Company.Name 
)

final_df = change_df

write.csv(final_df, "cleaned.csv")
