#setwd("C:/Users/mosu001/OneDrive - The University of Auckland/Documents/uoa/industry-engagement/PracWork")
setwd("C:/Data/PracWork")


library(dplyr)
library(tidyverse)
library(ggplot2)
raw_df <- read.csv("C:/Data/PracWork/practical_work_registration report 29-03-2023.csv")
sort_df <- raw_df[order(raw_df$Company.Name),]

invalid = c(
  "",
  "...",
  "5b Kindergarten Dr, Conifer Grove","#NAME?"
)

valid_df = sort_df[!(sort_df$Company.Name %in% invalid),]

needsChange = c(
  " (aerospace New Business Networks Company Limited)",
  "(fujian Liansheng Paper Industry Co., Ltd.)",
  "9spokes International Limited", "2022 Nz Robot Olympiad","9 Spokes","9 Spokes International","9spokes International","9spokes International Limited",
  "Abb Napier","Abb Nz Ltd", "Abb Ltd","Acciona Construction", "Accord Precision Machining","Ach Conuslting Ltd","Ach Consulting Engineers",
  "Active Engineering","Advanced Aerospace Ltd","Advanced Aerospace","Advanced Personal","Advanced Personnel Services Ltd","Aecom Nz",
  "Aecom Ltd","Aecom New Zealand Limited","Aecom New Zealand","Aeroqual Ltd","Air Liquide New Zealand Limited","Air Liquide New Zealand",
  "Air New Zealand Engineering Services","Airlab","Alchemy Systems Ltd","Alimetry Ltd.","Amazon Web Services New Zealand Limited","Amazon Web Services Nzl Ltd",
  "Amphenol Phitek Limited - Auckland, New Zealand","Apollo Living - Commercial  Residential","Apple New Zealand","Apple","Apple Technology Services (apple)",
  "Ar  Associated Ltd", "Aroa Biosurgery","Aroa Biosurgery Ltd","Aroa","Arup","Arup New Zealand", "Asb","Asb Bank","Asbuilt Digital","Asbuilt Ltd",
  "Asona Limited", "Aspec", "Atlassian Corporation Plc", "Auckland Bioengineering Institute","Auckland Bioengineering Institute - Empathic Computing Laboratory",
  "Auckland Bioengineering Institute, The University Of Auckland", "Auckland Bioengineering Institute (abi)", "Auckland Bio Engineering Institute",
  "Auckland Bioengineering Institute, University Of Auckland", "Auckland Bioengineering Institute - Implantable Devices Group",
  "Auckland Biomedical Engineering", "Auckland Space Institute - Te Pnaha tea","Auckland Uniservices Limited", "Auckland University",
  "Auckland University Maker Space", "Aurecon, Tauranga","Aurecon, New Zealand", "Aurecon Nz", "Aurecon New Zealand", "Aurecon New Zealand Limited",
  "Aurecon Group Ltd. - Auckland, New Zealand", "Aurecon New Zealand Ltd","Aurecon Group Ltd.", "Aurecon Group", "Aut School Of Science Research",
  "Aut Internship", "Aviat Networks Nz", "Awa Environmental", "Babbage Consultants Ltd.", "Babbage", "Babbage Consultants Ltd", "Babcock Australasia",
  "Babcock (nz) Ltd", "Babcock Australia  New Zealand", "Babcock Nz Ltd","Babcock International","Babcock International Nz", "Babcock Nz",
  "Babcock New Zealand", "Babcock Nz Ltd.", "Ballance-agri Nutrients", "Bank Of New Zealand - Wellington, New Zealand", "Bartley Consultants",
  "Bay Of Plenty Regional Council And Rotorua Lakes Council", "Bcd Group Limited", "Bc Group Nz", "Beca Wellington", "Beca - Wellington, New Zealand",
  "Beca Ltd", "Beca Limited", "Beca Group Ltd", "Beca Group Limited", "Beca Group", "Beca Ltd.", "Beca Group Limited.", "Beca Applied Technologies",
  "Biolumic Ltd", "Bison Group Limited", "Blue Barn Consulting Ltd.", "Blue Cars Ltd", "Bluelab Corporation", "Bricks4kidz", "Bricks 4 Kidz New Zealand",
  "Broad Solutions Limited", "Bsk Consulting Consultant Engineers", "Buckley Systems Limited", "Buckley Systems Ltd","Burohappold", "Calibre Consulting Limited",
  "Calibre Group New Zealand","Cares, University Of Auckland","Cares","Carrel Electrade Limited", "Cb Civil And Drainage Ltd","Cb Civil",
  "Cemix Products Ltd","Centre For Advanced Composite Materials - The University Of Auckland", "Chester Consultants Ltd.", "Chester Consultants",
  "China Construction Third Engineering Bureau Co.ltd", "Chorus New Zealand", "Cirrus Materials Science Ltd", "Cirrus Materials Science Limited",
  "City Care Ltd.", "Civil Plan", "Civilplan","Ckl","Claymark Profiles Ltd.", "Cll Service  Solutions","Cloudstore Limited", "Cnc Machining Co. Ltd",
  "Coca-cola Amatil", "Cognex", "Compac", "Compac Sorting Limited","Compac Sorting","Compac Sorting Equipment Ltd","Compliance Audit Systems Ltd",
  "Comprehensive Care Limited", "Contact Energy Ltd", "Contact Energy Limited","Coretex Nz Limited", "Cornerstone Engineering Consultants Ltd",
  "Cornerstone Engineering Consultants","Cornerstone Engineering Consultant", "Cosmos Building Limited", "Covertex", "Cpb Contractorws", "Crossfire, A Jensen Hughes Company",
  "Crossfire Fire Engineering", "Crown Equipment Corporation", "Crown Equipment", "Crown Equipment - Rtc", "Crown Rtc", "Crown Robotic Technology Centre",
  "Cse Consaultants Ltd", "Cse Consultants Limited", "Cubic Defense Nz","Cubic Defense New Zealand", "Daifuku Oceania Trading As Bcs New Zealand", "Daifuku",
  "Daikin New Zealand", "Datacom Group Ltd.", "Datacom Group Limited", "Datacom Group Ltd", "Datacom Ltd", "Datamars Tru-test Ltd",
  "Datamars Ltd", "Datamars New Zealand", "Datamars (tru-test)", "Datamars Limited", "Db Breweries Ltd Waitemata", "Db Breweries  Heineken",
  "Deloitte New Zealand", "Dempsey Wood Civil Limited", "Dempsey Wood Civil", "Dempsey Wood Civil Ltd.", "Department Of Engineering Science, The University Of Auckland",
  "Department Of Engineering Science, University Of Auckland", "Department Of Engineering Science", "Department Of Mechanical Engineering At The University Of Auckland",
  "Department Of Exercise Science", "Department Of Mathematics, The University Of Auckland", "Department Of Civil And Environmental Engineering, Faculty Of Engineering, University Of Auckland",
  "Department Of Chemical  Materials Engineering, University Of Auckland", "Design Production Ltd", "Developed", "Dhc Consulting Group Ltd",
  "Digital Sensing Limited  Manufacturing Systems Limited", "Direct Control Ltd", "Dn3010", "Dodd Civil Consultants Ltd", "Douglas Pharmaceuticals Ltd",
  "Downer Northern Region Depot", "Downer Nz", "Downer New Zealand", "Downer Nz Ltd", "Downer Nz (gisborne)", "Downer Group", "Downer New Zealand Limited", 
  "Downer Group Nz", "Downer Utilities Alliance New Zealand Limited", "Downer Nz Limted", "Downer Newzealand", "Downer Nz - Link Alliance",
  "Dreamcast Civil Ltd",  "Eaton Electrical Equipment Co., Ltd.", "Ecubed Building Workshop Ltd", "Eg Whiter Ltd", "Eighty6 Engineering", "Elite Mountain Home Limited",
  "Energy Solution Providers", "Engeo Limited", "Engex","Engineering Design Consultant",  "Engineering Design Consultants Ltd", "Engineering Science Department, The University Of Auckland", 
  "Engineous Consulting Ltd", "Ergo Consulting","Ernst  Young Limited",  "Ernst  Young (ey)", "Ernst And Young", "Ernst  Young New Zealand", "Ernst And Young Global Limited",
  "Eroad Ltd", "Etel", "Etel Limited","Ey - Ernst And Young", "Ey", "Eze Business Solutions", "Faculty Of Medical And Health Science  Auckland Bioengineering Institute (summer Research Scholarship)",
  "Faculty Of Medical And Health Sciences", "Faculty Of Engineering - University Of Auckland", "Faculty Of Engineering- The University Of Auckland", "Faculty Of Engineering, University Of Auckland",
  "Felton Industries", "Fergus", "Fergus Software", "Fergus Software Limited", "Figured Limited", "Fisher  Paykel Healthcare",
  "Fisherpaykel Healthcare","Fisher  Paykel","Fisher  Paykel Healthcare Limited", "Fisher  Paykel Healthcare Cooperation Limited", "Fisher And Paykel Heathcare", "Fisher  Paykel Healthcare Ltd.",
  "Fisher  Paykel Healthcare Corporation Limited",  "Fisher  Paykel Appliances",  "Fisher And Paykel",  "Fisherpaykel Appliances",  "Fisher  Paykel Appliances Holdings Ltd.",
  "Fisher  Paykel Appliances Ltd.", "Fisher  Paykel Appliances Ltd", "Fisher And Paykel Appliances Ltd.", "Fisher  Paykel", "Fisher  Paykel Technologies",
  "Fisher  Paykel", "Fisher Paykel Technologies", "Fletcher Building - Nx2", "Fletcher Building-higgins Contractors Limited",    "Fletcher Construction Ltd.",
  "Fletcher Construction (infrastructure)", "Fletcher Construction Company", "Fletcher Construction Ltd Trading As Brian Perry Civil", "Flexware Ltd.", "Flexware",
  "Flow Transportation Nz Ltd", "Flow Transportation Specialists Ltd", "Fnz Limited", "Fnz Services (new Zealand) Limited",  "Fonterra Research And Development Centre",
  "Fonterra Co-operative Group Limited", "Fonterra Co-operative Group Ltd.", "Foodstuffs North Island Limited", "Foodstuffs North Island Ltd","Foodstuffs","Foodstuffs North Island Limited", "Formsteel Technologies Ltd",
  "Formuslabs", "Fort Project", "Framecad", "Fraser Thomas Ltd", "Fraser Thomas", "Frequency Nz", "Fresco Shades Ltd", "Ftek",  "Fulton Hogan Civil","Fulton Hogan Limited", "Fulton Hogan John Holland Joint Venture",
  "Fulton Hogan Ltd.", "Fulton Hogan Ltd", "Fusion Entertainment Ltd.","Gaia Homes Limited", "Gallagher Group Limited", "Gea New Zealand", "Gengis Khan Mongolian Barbeque Resturant", "Gentrack Ltd.",
  "Gentrack Limited","Gentrack Ltd", "Geopro Limited", "Geotechnics Ltd", "Geotechnics Ltd.", "Geotechnics - Tonkin  Taylor", "Geovert", "Ghd Ltd","Ghd Limited","Ghd Group",
  "Ghd Hamilton","Ghd Consultants","Ghd (gutteridge Haskins  Davey) Group Pty Ltd","Ghd Group Nz", "Ghella Abergeldie Jv", "Ghella Abergeldie", "Gibbons Civil Engineering", "Gibbs Amphibians Ltd.",
  "Giles Civil Ltd.", "Glidepath Limited - Alstef Group", "Glidepath Limited (alstef Group)", "Gmp Pharmaceuticals Ltd", "Godwin-austen Construction Ltd", "Goldsworthy Sheetmetal 2016 Ltd",
  "Google Australia Pty Ltd", "Google New Zealand Ltd", "Green Air Products Ltd.", "Ground Investigation Ltd", "Gwe Consulting Ltd.","Gwe Consulting Limited",
 "Halter Ltd", "Halter Limited", "Hapara Inc. (cloud Dev Ltd.)", "Hapara", "Harmonic Analytics", "Harris Foster Consulting (hfc)","Harris Foster Consulting Group", "Hawk Group",
 "Hawkins- Auckland, New Zealand","Hawkins 2017 Ltd","Hawkins Construction Limited", "Hawkins Ltd.", "Healthcare Applications Limited", "Heb Construction Ltd","Heb", "Hectre Group Limited", "Heinz Wattie#s Ltd.", 
 "Heinz Wattie#s", "Heliase Analytics", "Heliase Analytics Ltd", "Henry Schein One New Zealand", "Hick Bros Civil", "Higgins Contractors Hawkes Bay","Higgins","Higgins Waikato", "Hilti New Zealand Ltd.",
 "Holmes", "Holmes Nz Lp", "Holmes Fire", "Hot Water Heat Pumps, Ltd", "Hp Homes Limited", "Huawei", "Hustle Labour Hire", "Hustle New Zealand Limited", "Hustle Labour Hire Auckland",
 "Hustle", "Hydraulic Analysis Ltd", "Hydraulink", "Hynds Piping Systems", "Ict (integrated Control Technology)", "Ideal Engineering Consultant", "Independent Traffic Control",
 "Infosys Limited", "Infosys Limited Nz", "Infosys Ltd", "Institute For Innovation And Improvement (i3) Waitemata Dhb", "Intdevice Ltd.", "Intdevice", "Integrated Control Technology Limited",
 "Integrated Control Technology (ict)", "Invenco", "Invoke Limited", "Iot Ventures Limited", "Iot Ventures Ltd", "Jacksco Civil", "Jackson Industries-electrical","Jackson Electrical Ltd", "Jacobs Solutions", "Jacobs Engineering Group Inc",
 "Jacobs New Zealand Ltd", "Jasper", "Jmp Engineering Ltd", "John Fillmore Contracting Ltd (jfc)", "John Fillmore Contracting Ltd. (jfc Ltd)", "Joyous Limited",
 "K Design Group Ltd", "Kalmar Construction Limited", "Kalmar Construction", "Kalmar", "Kami Ltd", "Kando", "Kaptura", "Kea Dynamics", "Kennedy Technologies", "Kerry Dines Limited", "Kinetic Engineering Design Ltd.",
 "Kinetic Engineering Design Ltd.", "Kirk Roberts Consulting Engineers Ltd.", "Kitchen Cabinets  Stones Ltd.", "Kitchen Cabinet And Stones", "Kitchen Cabinet Stones", "Kitchen Cabinet Stones Ltd",
 "Kiwi Vision Consultants Limited", "Kiwiplan Nz", "Kiwirail Group Limited", "Kiwirail Holdings Limited", "Kotahi Logistics Lp.", "Kpmg New Zealand", "La Bonne Cuisine Ltd. (kraft Heinz Ltd.)",
 "La Bonne Cuisine - Kraft Heinz", "Landworks Consulting", "Langslow Engineering Limited", "Leapthought Nz Limited", "Link Alliance (vinci)", "Link Alliance - Vinci Construction Grands Projects",
 "Lion Nz", "Livefirm Construction (n.i.) Limited", "Livefirm Construction (north Island) Limited", "Longchamps Group", "Long Champs Group Ltd", "Longchampsgroup",
 "Lovelive Ltd", "Lovelive Ltd.", "Lune Digital Ltd","Manufacturing Systems Limited","March Cato Developments Ltd","Marops Ltd", "Marshall Day Acoustics Ltd", "Martinus Rail Nz Ltd",
 "Maven Associates Limited", "Maven Associates", "Maxtel Software", "Maxtel Software Ltd.", "Mcconnell Dowell Constructors", "Mcconnell Dowell Constructors Ltd", "Mcconell Dowell", "Mcconnell Dowell Constructors Limited",
 "Mcconnell Dowell Constructors Ltd.", "Mckay Engineering", "Mckenzie  Co.", "Mckenzie And Co. Limited", "Mckenzieco", "Mckenzie  Parma", "Mckenzie And Co.", "Mclaren Automotive",
 "Mea Mobile Ltd", "Mea Mobile", "Melodics Ltd.", "Mercury Nz", "Mercury Nz Limited", "Mercure Auckland", "Mercury Nz Ltd", "Mercury Energy", "Mercury Nz Limited", "Methanex Corporation",
 "Methanex New Zealand Ltd.", "Methanex Nz Ltd", "Metis Consultants Limited", "Microsoft Corporation", "Mimomax Wireless Limited", "Ministry Of Business, Innovation, And Employment", "Ministry Of Business Innovation And Employment",
 "Ministry Of Social Development (msd)", "Mint Innovation", "Mitchell Vranjes", "Mitre 10 Mega Westgate", "Mitre 10 Onehunga", "Mitre 10 Mega Henderson", "Motorsport Electronics (msel)",
 "Much Moore Ice Cream Company", "Mutual Construction Ltd",  "Nanolayr Limited", "National Chung Cheng University(ccu)", "National  Chung Cheng University", "National Chung Chung University","National Formosa University","Nauhria Precast Limited",
 "Nautech Electroncis","Nautech Electroncis","Navico Auckland Ltd","Navico Auckland","Navico Group", "Navicom Dynamics Ltd", "Navicom Dynamics Limited","Nda", "New Zealand Frost Fans Ltd", "New Zealand Trade  Enterprise", "New Zealand#s Aluminium Smelters Limited (nzas)",
 "New Zealand#s Aluminium Smelter", "Ngawha Generation Ltd", "Nikau Robotics Limited", "Nikau Robotics Ltd", "Nintex", "Nintex Promapp Solutions Limited", "Nokia Shanghai Bell Co., Ltd", "Norman Disney And Young",
 "Oceanagold Corporation", "Oji Fibre Solutions - Kinleith Mill", "Oji Fibre Solutions - Tasman Mill", "Oji Fibre Solutions - Kinleith", "Oji Solutions", "Omc Electronics Nz Limited Ta Oppo New Zealand","Omron Electronics Limited",
 "Omv New Zealand", "Oppo New Zealand", "Optiver Asia Pacific", "Opum Technologies Ltd, Opum Us Inc", "Opzet Ltd.", "Orion Health Nz", "Outpost Central Limited", "Pacific Marine And Leisure","Pacific Marine Leisure Ltd - Auckland, New Zealand", "Pacific Marine",
 "Pan Pac Forests Products Limited", "Pattle Delamore Partners Limited", "Pattle Delamore Partners Ltd", "Pbtech Limited","Pb Technologies","Pb Technologies Ltd", "Pictor Ltd", "Pipers Intellectual Property", "Polymer Group Ltd.", "Poweron Ltd",
 "Ppg Industries New Zealand Limited", "Prescott Engineering (2015) Ltd.", "Prescott Engineering Ltd.", "Pricewaterhousecoopers Australia", "Primech Ltd", "Ptm Consultants Ltd", "Pushpay Holdings Limited","Pwc New Zealand",
 "Qm Development Limited","Qrious", "Quantifi Photonics", "Quantifi Photonics Ltd.", "Quantifi Photonics Limited", "Quantiful Ltd.","Quantiful Limited", "Quickcircuit", "Rakon Limited", "Rakon Nz Ltd",
 "Redwood Engineering Limited", "Resource Development Consultants Limited (rdcl)", "Rheem New Zealand Limited", "Rheem New Zealand Ltd", "Richards Consulting Engineers", "Riley Consultants Ltd.", "Riley Consultants","Rinnai New Zealand",
 "Rinnai Nz Ltd","Rinnai New Zealand Limited","Rinnai Nz, 105 Pavilion Drive", "Risosenterprises Ltd.", "Risosenterprises","Robinson Research Institute - Victoria University Of Wellington",
 "Robotics Plus Limited", "Robotics Plus", "Robotics Plus Inc","Rocket Lab Ltd.","Rocketlab", "Rocos Global Limited", "Ross Reid Contractors Ltd","Ross Reid Contractors Limited", "Royal New Zealand Air Force", "Ryman Healthcare Ltd",
 "Ryman Health Care","Ryman", "Safety Solutions Limited", "Sailgp","Sail Gp Technologies", "Sandfield Associates Limited", "Sandfield Associates",  "Sap New Zealand Ltd", "Schneuder Electric", "Scion", "Scratchpad Stonefields", "Scratchpad", "Seadragon Marine Oils Limited",
 "Sealegs International Limited","Sealegs International Ltd", "Serato Ltd", "Serko","Serko Limited", "Serko Ltd.", "Sharpeye Limited","Sharpeye", "Siemens Mobility New Zealand", "Silvester Clark Ltd.", "Simpson Shaw Surveyors", "Sistema Plastics", "Skinnyspark New Zealand",
 "Smart City Streets",  "Smx Email", "Soletanche Bachy - Link Alliance", "Southbase Construction Ltd", "Space Structural Consultants","Spark 64 Ltd.", "Spark Nz Ltd", "Spark New Zealand","Spark Nz Trading", "Spark New Zealand - Skinny", "Spark New Zealand Trading",
 "Spencer Holmes Limited", "Stantec New Zealand", "Stellar Projects","Stellar Projects Limited", "Stratum Consultants Limited", "Suez Smart Solutions Ltd","Suez Smart Solutions Nz","Suez Smart Solutions Limited", "Summer Research Scholarship At University Of Auckland",
 "Summer Research Scholarship - How Crime Against Women Deters Economic Growth Theory Meets Data", "Susquhanna International Group (sig)", "Swages", "Swages Engineering Limited",
 "Synlait Milk Auckland","Syrp", "Talegent Limited Partnership", "Tasman Engineering Company Ltd.", "Tasman Insulation New Zealand Limited", "Tasti Products Limited", "Tasti Products",  "Tci New Zealand 1995 Ltd", "Temperzone Limited",
 "Ten4 Transport Engineering", "Thales Group - Gtsnz", "The Fletcher Construction Company", "The Griffin#s Food Company", "The Labour Exchange Limited", "The Labour Exchange Ltd", "The Labour Exchange Ltd.", "The Roofing Store (ks Holdings)",
 "The Roofing Store Ltd - Ks Holdings Ltd", "The University Of Auckland Summer Research Scholarship", "The University Of Auckland-department Of Chemical And Material Engineering", "The University Of Auckland, Summer Research",
 "The University Of Auckland, Digital Services,", "The University Of Auckland Faculty Of Engineering", "The University Of Auckland - Learning Environment Support Unit", "The University Of Auckland Engineering Department",
 "The University Of Auckland - Summer Research Scholarship", "The University Of Auckland - Faculty Of Engineering", "The University Of Auckland - Faculty Of Medical And Health Sciences", "The University Of Auckland, Faculty Of Engineering",
 "The University Of Auckland School Of Environment", "The University Of Auckland Department Of Physics", "The University Of Auckland Waste  Resource Recovery Research Group", "The University Of Auckland (faculty Of Engineering)",
 "The University Of Auckland - School Of Computer Science", "The University Of Auckland - Faculty Of Business And Economics", "The University Of Auckland - Department Of Chemical And Materials Engineering", "The University Of Auckland - Chemical  Materials Department",
 "Thermosash Commerical Ltd", "Thl Design Group Limited", "Thl Design Group Ltd", "Tidy International Limited", "Tidy International (nz) Ltd", "Tilsley Engineering Ltd.",  "Tilsley Engineering Limited", "Tim Solution Ltd.", "Timi Construction Limited", "Tip Top Ice Cream Company",
 "Toki Recruitment Ltd  Fulton Hogan","Toki Recruitment Limited", "Tomra", "Tomra Food","Tomra Fresh Food  Compac", "Tonkin  Taylor Ltd", "Tonkin And Taylor", "Tonkin And Taylor Limited", "Top Energy Limited", "Toptec Construction Ltd", "Trade Me Ltd.", "Traffic Engineering Solutions Ltd",
 "Traffic Engineering Solutions Limited", "Traffic Engineering Solution", "Transpower New Zealand" = "Transpower","Transpower New Zealand Ltd","Transpower New Zealand Limited", "Trimble Navigation New Zealand Limited", "Trimble Navigation New Zealand Ltd",
 "Trimble, Inc.", "Unison Networks Limited", "University Of Auckland, Faculty Of Engineering","University Of Auckland Engineering Science Department",
 "University Of Auckland Ecse","University Of Auckland - Summer Research Scholarship","University Of Auckland Power Electronics Laboratory", "University Of Auckland - Faculty Of Medical Health Sciences","University Of Auckland (summer Research Scholarship)",
 "University Of Auckland (summer Research Scholarship)","University Of Auckland - Department Of Civil And Environmental Engineering","University Of Auckland, Faculty Of Engineering",
 "University Of Auckland Summer Research Scholarships","University Of Auckland, Department Of Exercise Sciences","University Of Auckland, Department Of Electrical, Computer And Software Engineering",
 "University Of Auckland Department Of Civil And Environmental Engineering","University Of Auckland - Faculty Of Engineering","University Of Auckland (property Services Team)","University Of Auckland - Department Of Chemical And Materials Engineering","University Of Auckland Cacm","University Of Auckland Faculty Of Medical And Health Sciences",
 "University Of Auckland - Faculty Of Engineering","University Of Auckland Faculty Of Medical And Health Sciences","University Of Auckland Formula Sae Team Inc.","University Of Auckland Faculty Of Engineering",
 "University Of Auckland, Faculty Of Engineering","University Of Auckland Department Of Engineering Science","University Of Auckland (auckland Space Insitute)","University Of Auckland - Faculty Of Engineering",
 "University Of Auckland, Robotics Research Group","University Of Auckland Faculty Of Engineering","University Of Auckland - Digital Services","University Of Auckland - Department Of Civil And Environmental Engineering",
 "University Of Auckland - Department Of Engineering Science","University Of Auckland Department Of Mathematics","University Of Auckland Faculty Of Civil And Environmental Engineering","University Of Auckland Bioengineering Institute","University Of Auckland, Newmarket Campus",
 "Unova Control Ltd",

 
 
  )
change <- c( 
  " (aerospace New Business Networks Company Limited)"="Aerospace New Business Networks Company Limited",
  "(fujian Liansheng Paper Industry Co., Ltd.)"="Fujian Liansheng Paper Industry Co., Ltd.",
  "9spokes International Limited"="9 Spokes International Limited",
  "2022 Nz Robot Olympiad" = "2022 Nz Robotics Olympiad",
  "22 Degrees Building Services Engineering"= "22 Degrees Ltd",
  "9 Spokes"="9 Spokes International Limited",
  "9 Spokes International"="9 Spokes International Limited",
  "9spokes International"="9 Spokes International Limited",
  "9spokes International Limited"="9 Spokes International Limited",
  "Abb Napier"="Abb",
  "Abb Nz Ltd"="Abb",
  "Abb Ltd"="Abb",
  "Acciona Construction"="Acciona",
  "Accord Precision Machining"="Accord Precision Cnc Machining",
  "Ach Consulting Engineers"="Ach Consulting Ltd",
  "Ach Conuslting Ltd"="Ach Consulting Ltd",
  "Active Engineering"="Active Engineering Limited",
  "Advanced Aerospace Ltd"="Advanced Aerospace Limited",
  "Advanced Aerospace"="Advanced Aerospace Limited",
  "Advanced Personal"="Advanced Personnel",
  "Advanced Personnel Services Ltd"="Advanced Personnel",
  "Aecom Nz"="Aecom",
  "Aecom Ltd"="Aecom",
  "Aecom New Zealand Limited"="Aecom",
  "Aecom New Zealand"="Aecom",
  "Aeroqual Ltd"="Aeroqual",
  "Air Liquide New Zealand"="Air Liquide",
  "Air Liquide New Zealand Limited"="Air Liquide",
  "Air New Zealand Engineering Services"="Air New Zealand",
  "Airlab"="Airlab Ltd",
  "Alchemy Systems Ltd"="Alchemy Systems Limited",
  "Alimetry Ltd."="Alimetry",
  "Amazon Web Services New Zealand Limited"="Amazon Web Services",
  "Amazon Web Services Nzl Ltd"="Amazon Web Services",
  "Amphenol Phitek Limited - Auckland, New Zealand"="Amphenol Phitek Limited",
  "Apollo Living - Commercial  Residential"="Apolloliving Limited",
  "Apple"="Apple Inc.",
  "Apple New Zealand"="Apple Inc.",
  "Apple Technology Services (apple)"="Apple Inc.",
  "Ar  Associated Ltd"="Ar  Associates Ltd",
  "Aroa Biosurgery"="Aroa Biosurgery Limited",
  "Aroa Biosurgery Ltd"="Aroa Biosurgery Limited",
  "Aroa"="Aroa Biosurgery Limited",
  "Arup"="Arup New Zealand Limited",
  "Arup New Zealand"="Arup New Zealand Limited",
  "Asb"="Asb Bank Limited",
  "Asb Bank"="Asb Bank Limited",
  "Asbuilt Ltd"="Asbuilt",
  "Asbuilt Digital"="Asbuilt",
  "Asona Limited"="Asona",
  "Aspec"="Aspec Construction",
  "Atlassian Corporation Plc"="Atlassian",
  "Auckland Bioengineering Institute"="The University of Auckland",
  "Auckland Bioengineering Institute - Empathic Computing Laboratory"="The University of Auckland",
  "Auckland Biomedical Engineering"="The University of Auckland",
  "Auckland Bioengineering Institute, The University Of Auckland"="The University of Auckland",
  "Auckland Bioengineering Institute (abi)"="The University of Auckland",
  "Auckland Bio Engineering Institute"="The University of Auckland",
  "Auckland Bioengineering Institute, University Of Auckland"="The University of Auckland",
  "Auckland Bioengineering Institute - Implantable Devices Group"="The University of Auckland",
  "Auckland Space Institute - Te Pnaha tea"="The University of Auckland",
  "Auckland Uniservices Limited"="The University of Auckland",
  "Auckland University"="The University of Auckland",
  "Auckland University Maker Space"="The University of Auckland",
  "Aurecon, Tauranga"="Aurecon Group Ltd",
  "Aurecon, New Zealand"="Aurecon Group Ltd",
  "Aurecon Nz"="Aurecon Group Ltd",
  "Aurecon New Zealand"="Aurecon Group Ltd",
  "Aurecon New Zealand Limited"="Aurecon Group Ltd",
  "Aurecon Group Ltd."="Aurecon Group Ltd",
  "Aurecon Group Ltd. - Auckland, New Zealand"="Aurecon Group Ltd",
  "Aurecon New Zealand Ltd"="Aurecon Group Ltd",
  "Aurecon Group"="Aurecon Group Ltd",
  "Aut School Of Science Research"="Aut",
  "Aut Internship"="Aut",
  "Aviat Networks Nz"="Aviat Networks",
  "Awa Environmental"="Awa Environmental Ltd",
  "Babbage Consultants Ltd." = "Babbage Consultants",
  "Babbage" = "Babbage Consultants", 
  "Babbage Consultants Ltd" = "Babbage Consultants", 
  "Babcock Australasia" = "Babcock",
  "Babcock (nz) Ltd" = "Babcock",
  "Babcock Australia  New Zealand" = "Babcock",
  "Babcock Nz Ltd" = "Babcock",
  "Babcock International" = "Babcock",
  "Babcock International Nz" = "Babcock",
  "Babcock Nz" = "Babcock",
  "Babcock New Zealand" = "Babcock",
  "Babcock Nz Ltd." = "Babcock",
  "Ballance-agri Nutrients" = "Ballance Agri-nutrients",
  "Bank Of New Zealand - Wellington, New Zealand" = "Bank Of New Zealand",
  "Bartley Consultants" = "Bartley Consultants Limited",
  "Bay Of Plenty Regional Council And Rotorua Lakes Council" = "Bay Of Plenty Regional Council",
  "Bc Group Nz" = "Bcd Group",
  "Bcd Group Limited" = "Bcd Group",
  "Beca Wellington" = "Beca",
  "Beca - Wellington, New Zealand" = "Beca",
  "Beca Ltd" = "Beca",
  "Beca Limited" = "Beca",
  "Beca Group Ltd" = "Beca",
  "Beca Group Limited" = "Beca",
  "Beca Group" = "Beca",
  "Beca Ltd." = "Beca",
  "Beca Group Limited." = "Beca",
  "Beca Applied Technologies" = "Beca",
  "Biolumic Ltd" = "Biolumic",
  "Bison Group Limited" = "Bison Group",
  "Blue Barn Consulting Ltd."="Blue Barn",
  "Blue Cars Ltd" ="Blue Cars",
  "Bluelab Corporation" = "Bluelab",
  "Bricks 4 Kidz New Zealand"="Bricks 4 Kidz",
  "Bricks4kidz"="Bricks 4 Kidz",
  "Broad Solutions Limited" = "Broad Solutions",
  "Bsk Consulting Consultant Engineers" = "Bsk Consulting Engineers",
  "Buckley Systems Ltd" = "Buckley Systems",
  "Buckley Systems Limited" = "Buckley Systems",
  "Bunnings Warehouse Ltd" = "Bunnings Warehouse",
  "Burohappold" = "Burohapp",
  "Calibre Consulting Limited" = "Calibre Consulting",
  "Calibre Group New Zealand" = "Calibre Consulting",
  "Cares" = "Cares University Of Auckland",
  "Cares, University Of Auckland" = "Cares University Of Auckland",
  "Carrel Electrade Limited" = "Carrel Electrade Ltd",
  "Cb Civil" = "Cb Civil  Drainage",
  "Cb Civil And Drainage Ltd" = "Cb Civil  Drainage",
  "Cemix Products Ltd"="Cemix",
  "Centre For Advanced Composite Materials - The University Of Auckland" = "Centre For Advanced Composite Materials",
  "Chester Consultants Ltd."="Chester Consultants Ltd",
  "Chester Consultants"="Chester Consultants Ltd",
  "China Construction Third Engineering Bureau Co.ltd" = "China Construction Third Engineering Bureau Group Co.,ltd",
  "Chorus New Zealand"="Chorus",
  "Cirrus Materials Science Ltd" = "Cirrus Materials Science",
  "Cirrus Materials Science Limited" ="Cirrus Materials Science", 
  "City Care Ltd." = "City Care Goup",
  "City Rail Link Limited" = "City Rail Link",
  "City Rail Linkconnectus Jv" = "City Rail Link",
  "Civil Plan" = "Civilplan Consultants Limited",
  "Civilplan" = "Civilplan Consultants Limited",
  "Ckl" = "Ckr Homes",
  "Claymark Profiles Ltd." = "Claymark Group Limited Partnership",
  "Cll Service  Solutions" = "Cll Services And Solutions",
  "Cloudstore Limited" = "Cloudstore",
  "Cnc Machining Co. Ltd" = "Cnc Machining Co Ltd",
  "Coca-cola Amatil" = "Coca Cola Amatil",
  "Cognex" = "Cognex Corporation",
  "Compac Sorting Limited" = "Compac Sorting Equipment",
  "Compac" = "Compac Sorting Equipment",
  "Compac Sorting" = "Compac Sorting Equipment",
  "Compac Sorting Equipment Ltd" = "Compac Sorting Equipment",
  "Compliance Audit Systems Ltd" = "Compliance Audit Systems",
  "Comprehensive Care Limited" = "Comprehensive Care Ltd",
  "Contact Energy Limited" = "Contact Energy",
  "Contact Energy Ltd" = "Contact Energy",
  "Coretex Nz Limited" = "Coretex",
  "Cornerstone Engineering Consultants Ltd" = "Cornerstone Engineering Consultants Limited",
  "Cornerstone Engineering Consultants" = "Cornerstone Engineering Consultants Limited",
  "Cornerstone Engineering Consultant" = "Cornerstone Engineering Consultants Limited",
  "Cosmos Building Limited" = "Cosmos Building Ltd",
  "Covertex" = "Covertex Ltd",
  "Cpb Contractorws" = "Cpb Contractors",
  "Crossfire, A Jensen Hughes Company" = "Crossfire",
  "Crossfire Fire Engineering" = "Crossfire",
  "Crown Equipment Corporation" = "Crown Equipment Limited",
  "Crown Equipment - Rtc" = "Crown Equipment Limited",
  "Crown Equipment" = "Crown Equipment Limited",
  "Crown Rtc" = "Crown Equipment Limited",
  "Crown Robotic Technology Centre" = "Crown Equipment Limited",
  "Cse Consultants Limited" = "Cse Consultants Ltd",
  "Cse Consaultants Ltd" = "Cse Consultants Ltd",
  "Cubic Defense Nz" = "Cubic Defence New Zealand",
  "Cubic Defense New Zealand" = "Cubic Defence New Zealand",
  "Daifuku" = "Daifuku Oceania",
  "Daifuku Oceania Trading As Bcs New Zealand" = "Daifuku Oceania",
  "Daikin New Zealand" = "Daikin Air Conditioning Nz Ltd",
  "Datacom Ltd" = "Datacom",
  "Datacom Group Ltd" = "Datacom",
  "Datacom Group Limited" = "Datacom",
  "Datacom Group Ltd." = "Datacom",
  "Datamars Tru-test Ltd" = "Datamars",
  "Datamars Ltd" = "Datamars",
  "Datamars New Zealand" = "Datamars",
  "Datamars (tru-test)" = "Datamars",
  "Datamars Limited" = "Datamars",
  "Db Breweries  Heineken" = "Db Breweries",
  "Db Breweries Ltd Waitemata" = "Db Breweries",
  "Deloitte New Zealand" = "Deloitte",
  "Dempsey Wood Civil Ltd." = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil Limited" = "Dempsey Wood",
  "Department Of Engineering Science, The University Of Auckland" = "The University Of Auckland",
  "Department Of Engineering Science, University Of Auckland" = "The University Of Auckland",
  "Department Of Engineering Science" = "The University Of Auckland",
  "Department Of Mechanical Engineering At The University Of Auckland" = "The University Of Auckland",
  "Datacom Group Ltd." = "The University Of Auckland",
  "Department Of Exercise Science" = "The University Of Auckland",
  "Department Of Mathematics, The University Of Auckland" = "The University Of Auckland",
  "Department Of Civil And Environmental Engineering, Faculty Of Engineering, University Of Auckland" = "The University Of Auckland",
  "Department Of Chemical  Materials Engineering, University Of Auckland" = "The University Of Auckland",
  "Design Production Ltd" = "Design Production",
  "Developed" = "Developed Consultants Ltd",
  "Dhc Consulting Group Ltd" = "Dhc Consulting Ltd",
  "Digital Sensing Limited  Manufacturing Systems Limited" = "Digital Sensing Limited",
  "Direct Control Ltd" = "Direct Control",
  "Dn3010" = "Dn 3010 Limited",
  "Dodd Civil Consultants Ltd" = "Dodd Civil Consultants",
  "Douglas Pharmaceuticals Ltd" = "Douglas Pharmaceuticals",
  "Downer New Zealand" = "Downer",
  "Downer Group Nz" = "Downer",
  "Downer Nz" = "Downer",
  "Downer Group" = "Downer",
  "Downer Nz - Link Alliance" = "Downer",
  "Downer Newzealand" = "Downer",
  "Downer Nz Ltd" = "Downer",
  "Downer Nz Limted" = "Downer",
  "Downer New Zealand Limited" = "Downer",
  "Downer Utilities Alliance New Zealand Limited" = "Downer",
  "Downer Nz (gisborne)" = "Downer",
  "Downer Northern Region Depot" = "Downer",
  "Dreamcast Civil Ltd" = "Dreamcast Group",
  "Eaton Electrical Equipment Co., Ltd." = "Eaton Electrical Equipment Co., Ltd",
  "Ecubed Building Workshop Ltd" = "Ecubed",
  "Eg Whiter Ltd" = "Eg Whiter",
  "Eighty6 Engineering" = "Eighty6 Engineering Limited",
  "Elite Mountain Home Limited" = "Elite Mountain Homes Ltd",
  "Energy Solution Providers" = "Energy Solution Providers Ltd",
  "Engeo Limited" = "Engeo",
  "Engex" = "Engex Ltd",
  "Engineering Design Consultant" = "Engineering Design Consultants",
  "Engineering Design Consultants Ltd" = "Engineering Design Consultants",
  "Engineering Science Department, The University Of Auckland" = "The University Of Auckland",
  "Engineous Consulting Ltd" = "Engineous Consulting",
  "Ergo Consulting" = "Ergo Consulting Ltd",
  "Ernst  Young Limited" = "Ernst  Young",
  "Ernst  Young (ey)" = "Ernst  Young",
  "Ernst And Young" = "Ernst  Young",
  "Ernst And Young Global Limited" = "Ernst  Young",
  "Ernst  Young New Zealand" = "Ernst  Young",
  "Eroad Ltd" = "Eroad",
  "Etel Limited" = "Etel Transformers Ltd",
  "Etel" = "Etel Transformers Ltd",
  "Ey - Ernst And Young" = "Ernst  Young",
  "Ey" = "Ernst  Young",
  "Eze Business Solutions" = "Eze Business Solutions Ltd",
  "Faculty Of Medical And Health Science  Auckland Bioengineering Institute (summer Research Scholarship)" = "The University Of Auckland",
  "Faculty Of Medical And Health Sciences" = "The University Of Auckland",
  "Faculty Of Engineering - University Of Auckland" = "The University Of Auckland",
  "Faculty Of Engineering- The University Of Auckland" = "The University Of Auckland",
  "Faculty Of Engineering, University Of Auckland" = "The University Of Auckland",
  "Felton Industries" = "Felton Industries Ltd",
  "Fergus" = "Fergus Software Ltd",
  "Fergus Software" = "Fergus Software Ltd",
  "Fergus Software Limited" = "Fergus Software Ltd",
  "Figured Limited" = "Figured",
  "Fisher  Paykel Healthcare" = "Fisher And Paykel Healthcare",
  "Fisherpaykel Healthcare" = "Fisher And Paykel Healthcare",
  "Fisher  Paykel" = "Fisher And Paykel Healthcare",
  "Fisher  Paykel Healthcare Limited" = "Fisher And Paykel Healthcare",
  "Fisher  Paykel Healthcare Cooperation Limited" = "Fisher And Paykel Healthcare",
  "Fisher And Paykel Heathcare" = "Fisher And Paykel Healthcare",
  "Fisher  Paykel Healthcare Ltd." = "Fisher And Paykel Healthcare",
  "Fisher  Paykel Healthcare Corporation Limited" = "Fisher And Paykel Healthcare",
  "Fisher  Paykel"= "Fisher And Paykel Healthcare",
  "Fisher  Paykel Appliances" = "Fisher And Paykel Appliances",
  "Fisher And Paykel" = "Fisher And Paykel Appliances",
  "Fisherpaykel Appliances" = "Fisher And Paykel Appliances",
  "Fisher  Paykel Appliances Holdings Ltd." = "Fisher And Paykel Appliances",
  "Fisher  Paykel Appliances Ltd." = "Fisher And Paykel Appliances",
  "Fisher  Paykel Appliances Ltd" = "Fisher And Paykel Appliances",
  "Fisher And Paykel Appliances Ltd." = "Fisher And Paykel Appliances",
  "Fisher  Paykel Technologies" = "Fisher And Paykel Technologies",
  "Fisher  Paykel" = "Fisher And Paykel Technologies",
  "Fisher Paykel Technologies" = "Fisher And Paykel Technologies",
  "Fletcher Building - Nx2" = "Fletcher Building",
  "Fletcher Building-higgins Contractors Limited" = "Fletcher Building",
  "Fletcher Construction Ltd." = "Fletcher Construction",
  "Fletcher Construction (infrastructure)" = "Fletcher Construction",
  "Fletcher Construction Company" = "Fletcher Construction",
  "Fletcher Construction Ltd Trading As Brian Perry Civil" = "Fletcher Construction",
  "Fletchers" = "Fletcher Building",
  "Flexware Ltd." = "Flexware Ltd",
  "Flexware" = "Flexware Ltd",
  "Flow Transportation Nz Ltd" = "Flow Transportation Specialists",
  "Flow Transportation Specialists Ltd" = "Flow Transportation Specialists",
  "Fnz Services (new Zealand) Limited" = "Fnz",
  "Fnz Limited" = "Fnz",
  "Fonterra Research And Development Centre" = "Fonterra",
  "Fonterra Co-operative Group Limited" = "Fonterra",
  "Fonterra Co-operative Group Ltd." = "Fonterra",
  "Foodstuffs North Island Limited" = "Foodstuffs North Island",
  "Foodstuffs North Island Ltd" = "Foodstuffs North Island",
  "Foodstuffs" = "Foodstuffs North Island",
  "Foodstuffs North Island Limited" = "Foodstuffs North Island",
  "Formsteel Technologies Ltd" = "Formsteel",
  "Formuslabs" = "Formus Labs",
  "Fort Project" = "Fort Projects Ltd",
  "Framecad" = "Framecad Ltd",
  "Fraser Thomas Ltd" = "Fraser Thomas Limited",
  "Fraser Thomas" = "Fraser Thomas Limited",
  "Frequency Nz" = "Frequency",
  "Fresco Shades Ltd" = "Fresco Shades",
  "Ftek" = "Ftek Limited",
  "Fulton Hogan Civil" = "Fulton Hogan",
  "Fulton Hogan Limited" = "Fulton Hogan",
  "Fulton Hogan John Holland Joint Venture" = "Fulton Hogan",
  "Fulton Hogan Ltd." = "Fulton Hogan",
  "Fulton Hogan Ltd" = "Fulton Hogan",
  "Fusion Entertainment Ltd." = "Fusion Entertainment Ltd",
  "Gaia Homes Limited" = "Gaia Homes Ltd",
  "Gallagher Group Limited" = "Gallagher",
  "Gea New Zealand" = "Gea",
  "Gengis Khan Mongolian Barbeque Resturant" = "Gengis Khan Mongolian Restaurant",
  "Gentrack Ltd." = "Gentrack",
  "Gentrack Limited" = "Gentrack",
  "Gentrack Ltd" = "Gentrack",
  "Geopro Limited" = "Geopro Ltd",
  "Geotechnics Ltd" = "Dempsey Wood",
  "Geotechnics Ltd." = "Dempsey Wood",
  "Geotechnics - Tonkin  Taylor" = "Dempsey Wood",
  "Geovert" = "Geovert Ltd",
  "Ghd Ltd" = "Ghd",
  "Ghd Limited" = "Ghd",
  "Ghd Group" = "Ghd",
  "Ghd Hamilton" = "Ghd",
  "Ghd Consultants" = "Ghd",
  "Ghd (gutteridge Haskins  Davey) Group Pty Ltd" = "Ghd",
  "Ghd Group Nz" = "Ghd",
  "Ghella Abergeldie Jv" = "Ghella Abergeldie Joint Venture",
  "Ghella Abergeldie" = "Ghella Abergeldie Joint Venture",
  "Gibbons Civil Engineering" = "Gibbons Civil Engineering Ltd",
  "Gibbs Amphibians Ltd." = "Gibbs Group",
  "Giles Civil Ltd." = "Giles Civil Ltd",
  "Glidepath Limited - Alstef Group" = "Glidepath",
  "Glidepath Limited (alstef Group)" = "Glidepath",
  "Gmp Pharmaceuticals Ltd" = "Gmp Pharmaceuticals",
  "Godwin-austen Construction Ltd" = "Godwin - Austen Constructions Ltd",
  "Goldsworthy Sheetmetal 2016 Ltd" = "Goldsworthy Sheetmetal",
  "Google Australia Pty Ltd" = "Google",
  "Google New Zealand Ltd" = "Google",
  "Green Air Products Ltd." = "Green Air Products Ltd",
  "Ground Investigation Ltd" = "Ground Investigation",
  "Gwe Consulting Ltd." = "Gwe Consulting Ltd",
  "Gwe Consulting Limited" = "Gwe Consulting Ltd",
  "Halter Limited" = "Halter",
  "Halter Ltd" = "Halter",
  "Hapara Inc. (cloud Dev Ltd.)" = "Hapara Inc.",
  "Hapara" = "Hapara Inc.",
  "Harmonic Analytics" = "Harmonic Analytics Limited",
  "Harris Foster Consulting (hfc)" = "Harris Foster Consulting Limtied",
  "Harris Foster Consulting Group" = "Harris Foster Consulting Limtied",
  "Hawk Group" = "Hawk Group Ltd",
  "Hawkins- Auckland, New Zealand" = "Hawkins",
  "Hawkins 2017 Ltd" = "Hawkins",
  "Hawkins Construction Limited" = "Hawkins",
  "Hawkins Ltd." = "Hawkins",
  "Healthcare Applications Limited" = "Healthcare Applications Ltd",
  "Heb Construction Ltd" = "Heb Construction",
  "Heb" = "Heb Construction",
  "Hectre Group Limited" = "Hectre",
  "Heinz Wattie#s" = "Heinz Watties",
  "Heinz Wattie#s Ltd." = "Heinz Watties",
  "Heliase Analytics" = "Heliase",
  "Heliase Analytics Ltd" = "Heliase",
  "Henry Schein One New Zealand" = "Henry Schein One",
  "Hick Bros Civil" = "Hick Bros Civil Construction",
  "Higgins Contractors Hawkes Bay" = "Higgins Contractors Ltd",
  "Higgins" = "Higgins Contractors Ltd",
  "Higgins Waikato" = "Higgins Contractors Ltd",
  "Hilti New Zealand Ltd." = "Hilti Nz",
  "Holmes" = "Holmes Consulting",
  "Holmes Fire" = "Holmes Consulting",
  "Holmes Nz Lp" = "Holmes Consulting",
  "Hot Water Heat Pumps, Ltd" = "Hot Water Heat Pumps Ltd",
  "Hp Homes Limited" = "Hp Home Limited",
  "Huawei" = "Huawei Technologies New Zealand",
  "Hustle Labour Hire" = "Hustle",
  "Hustle New Zealand Limited" = "Hustle",
  "Hustle Labour Hire Auckland" = "Hustle",
  "Hydraulink" = "Hydraulic Analysis Limited",
  "Hydraulic Analysis Ltd" = "Hydraulic Analysis Limited",
  "Hynds Piping Systems" = "Hynds Pipe Systems",
  "Ict (integrated Control Technology)" = "Ict",
  "Ideal Engineering Consultant" = "Ideal Engineering Consultants Limited",
  "Independent Traffic Control" = "Independent Traffic Control Limited",
  "Infosys Ltd" = "Infosys",
  "Infosys Limited" = "Infosys",
  "Infosys Limited Nz" = "Infosys",
  "Institute For Innovation And Improvement (i3) Waitemata Dhb" = "Institute For Innovation  Improvement - Waitemata Dhb",
  "Intdevice" = "Intdevice Ltd",
  "Intdevice Ltd." = "Intdevice Ltd",
  "Integrated Control Technology Limited" = "Integrated Control Technology",
  "Integrated Control Technology (ict)" = "Integrated Control Technology",
  "Invenco" = "Invenco Group Limited",
  "Invoke Limited" = "Invoke Ltd",
  "Iot Ventures Ltd" = "Iot Ventures",
  "Iot Ventures Limited" = "Iot Ventures",
  "Jacksco Civil" = "Jacksco",
  "Jackson Industries-electrical" = "Jackson Industries Electrical",
  "Jackson Electrical Ltd" = "Jackson Industries Electrical",
  "Jacobs New Zealand Ltd" = "Jacobs",
  "Jacobs Engineering Group Inc" = "Jacobs",
  "Jacobs Solutions" = "Jacobs",
  "Jasper" = "Jasper Property Limited",
  "Jmp Engineering Ltd" = "Jmp Engineering",
  "John Fillmore Contracting Ltd (jfc)" = "John Fillmore Contracting",
  "John Fillmore Contracting Ltd. (jfc Ltd)" = "John Fillmore Contracting",
  "Joyous Limited" = "Joyous",
  "Joyous Limited" = "Joyous",
  "K Design Group Ltd" = "K Design Group",
  "Kalmar Construction Limited" = "Kalmar Construction Ltd",
  "Kalmar Construction" = "Kalmar Construction Ltd",
  "Kalmar" = "Kalmar Construction Ltd",
  "Kami Ltd" = "Kami",
  "Kando" = "Kando Innovation",
  "Kaptura" = "Kaptura Limited",
  "Kea Dynamics" = "Kea Dynamics Ltd",
  "Kennedy Technologies" = "Kennedy Technologies Ltd",
  "Kerry Dines Limited" = "Kerry Dines Ltd",
  "Kinetic Engineering Design Ltd." = "Kinetic Engineering Design Ltd",
  "Kirk Roberts Consulting Engineers Ltd." = "Kirk Roberts Consulting",
  "Kitchen Cabinet Stones Ltd" = "Kitchen Cabinets And Stones",
  "Kitchen Cabinet Stones" = "Kitchen Cabinets And Stones",
  "Kitchen Cabinets  Stones Ltd." = "Kitchen Cabinets And Stones",
  "Kitchen Cabinet And Stones" = "Kitchen Cabinets And Stones",
  "Kiwi Vision Consultants Limited" = "Kiwi Vision Consultants",
  "Kiwiplan Nz" = "Kiwiplan",
  "Kiwirail Group Limited" = "Kiwirail",
  "Kiwirail Holdings Limited" = "Kiwirail",
  "Kotahi Logistics Lp." = "Kotahi Logistics Lp",
  "Kpmg New Zealand" = "Kpmg",
  "La Bonne Cuisine - Kraft Heinz" = "La Bonne Cuisine",
  "La Bonne Cuisine Ltd. (kraft Heinz Ltd.)" = "La Bonne Cuisine",
  "Labour Exchange Ltd" = "Labour Exchange",
  "Labour Exchage" = "Labour Exchange",
  "Landworks Consulting" = "Landworks Consulting Ltd",
  "Langslow Engineering Limited" = "Langslow Engineering",
  "Langslow Engineering Limited" = "Langslow Engineering",
  "Leapthought Nz Limited" = "Leapthought Nz Ltd",
  "Link Alliance (vinci)" = "Link Alliance",
  "Link Alliance - Vinci Construction Grands Projects" = "Link Alliance",
  "Lion Nz" = "Lion",
  "Livefirm Construction (n.i.) Limited" = "Livefirm Construction Limited",
  "Livefirm Construction (north Island) Limited" = "Livefirm Construction Limited",
  "Longchampsgroup" = "Long Champs Group",
  "Long Champs Group Ltd" = "Long Champs Group",
  "Longchamps Group" = "Long Champs Group",
  "Lovelive Ltd" = "Dempsey Wood",
  "Lovelive Ltd." = "Dempsey Wood",
  "Lune Digital Ltd" = "Lune Digital",
  "Manufacturing Systems Limited" = "Manufacturing Systems Ltd",
  "March Cato Developments Ltd" = "March Cato",
  "Marops Ltd" = "Marops",
  "Marshall Day Acoustics Ltd" = "Marshall Day Acoustics",
  "Martinus Rail Nz Ltd" = "Martinus Rail",
  "Maven Associates Limited" = "Maven",
  "Maven Associates" = "Maven",
  "Maxtel Software" = "Maxtel",
  "Maxtel Software Ltd." = "Maxtel",
  "Mcconnell Dowell Constructors" = "Mcconnell Dowell",
  "Mcconnell Dowell Constructors Ltd" = "Mcconnell Dowell",
  "Mcconell Dowell" = "Mcconnell Dowell",
  "Mcconnell Dowell Constructors Limited" = "Mcconnell Dowell",
  "Mcconnell Dowell Constructors Ltd." = "Mcconnell Dowell",
  "Mckenzie  Co." = "Mckenzie And Co",
  "Mckenzie And Co. Limited" = "Mckenzie And Co",
  "Mckenzieco" = "Mckenzie And Co",
  "Mckenzie  Parma" = "Mckenzie And Co",
  "Mckenzie And Co." = "Mckenzie And Co",
  "Mea Mobile Ltd", "Mea Mobile",
  "Mea Mobile Ltd" = "Mea Mobile Limited",
  "Mea Mobile" = "Mea Mobile Limited",
  "Mercury Nz" = "Mercury",
  "Mercury Nz Limited" = "Mercury",
  "Mercure Auckland" = "Mercury",
  "Mercury Nz Ltd" = "Mercury",
  "Mercury Energy" = "Mercury",
  "Methanex Corporation" = "Methanex",
  "Methanex New Zealand Ltd." = "Methanex",
  "Methanex Nz Ltd" = "Methanex",
  "Metis Consultants Limited" = "Metis Consultants",
  "Microsoft Corporation" = "Microsoft",
  "Ministry Of Business, Innovation, And Employment" = "Ministry Of Business, Innovation And Employment",
  "Ministry Of Business Innovation And Employment" = "Ministry Of Business, Innovation And Employment",
  "Ministry Of Social Development (msd)" = "Ministry Of Social Development",
  "Mint Innovation" = "Mint",
  "Mitchell Vranjes" = "Mitchell Vranjes Structural Engineers",
  "Mitre 10 Mega Westgate" = "Mitre 10",
  "Mitre 10 Onehunga" = "Mitre 10",
  "Mitre 10 Mega Henderson" = "Mitre 10",
  "Motorsport Electronics (msel)" = "Motorsport Electronics",
  "Much Moore Ice Cream Company" = "Muchmoore",
  "Mutual Construction Ltd" = "Mutual Construction",
  "Nanolayr Limited" = "Nanolayr",
  "National Chung Cheng University(ccu)" = "National Chung Cheng University",
  "National  Chung Cheng University" = "National Chung Cheng University",
  "National Chung Chung University" = "National Chung Cheng University",
  "National Formosa University" = "National Formusa University",
  "Nauhria Precast Limited" = "Nauhria Precast Ltd",
  "Nautech Electroncis" = "Nautech Electronics",
  "Navico Auckland Ltd" = "Navico",
  "Navico Auckland" = "Navico",
  "Navico Group" = "Navico",
  "Navicom Dynamics Ltd" = "Navicom Dynamics",
  "Navicom Dynamics Limited" = "Navicom Dynamics",
  "Nda" = "Nda Engineering",
  "New Zealand Frost Fans Ltd" = "New Zealand Frost Fans",
  "New Zealand Trade  Enterprise" = "New Zealand Trade And Enterprise",
  "New Zealand#s Aluminium Smelters Limited (nzas)" = "New Zealand Aluminium Smelter",
  "New Zealand#s Aluminium Smelter" = "New Zealand Aluminium Smelter",
  "Ngawha Generation Ltd" = "Ngawha Generation",
  "Nikau Robotics Limited" = "Nikau Robotics",
  "Nikau Robotics Ltd" = "Nikau Robotics",
  "Nintex" = "Nintex Promapp",
  "Nintex Promapp Solutions Limited" = "Nintex Promapp",
  "Nokia Shanghai Bell Co., Ltd" = "Nokia Shanghai Bell",
  "Norman Disney And Young" = "Norman Disney  Young",
  "Oceanagold Corporation" = "Oceanagold",
  "Oji Fibre Solutions - Tasman Mill" = "Oji Fibre Solutions",
  "Oji Fibre Solutions - Kinleith" = "Oji Fibre Solutions",
  "Oji Fibre Solutions - Kinleith Mill" = "Oji Fibre Solutions",
  "Oji Solutions" = "Oji Fibre Solutions",
  "Omc Electronics Nz Limited Ta Oppo New Zealand" = "Omc Electronics Nz Limited",
  "Omron Electronics Limited" = "Omron Electronics Ltd",
  "Omv New Zealand" = "Omv Nz",
  "Oppo New Zealand" = "Oppo",
  "Optiver Asia Pacific" = "Optiver",
  "Opum Technologies Ltd, Opum Us Inc" = "Opum Technologies",
  "Opzet Ltd." = "Opzet Construction Company Limited",
  "Orion Health Nz" = "Orion Health",
  "Outpost Central Limited" = "Outpost Central",
  "Pacific Marine And Leisure" = "Pacific Marine  Leisure Ltd",
  "Pacific Marine Leisure Ltd - Auckland, New Zealand" = "Pacific Marine  Leisure Ltd",
  "Pacific Marine" = "Pacific Marine  Leisure Ltd",
  "Pan Pac Forests Products Limited" = "Pan Pac Forest Products Limited",
  "Pattle Delamore Partners Limited" = "Pattle Delamore Partners",
  "Pattle Delamore Partners Ltd" = "Pattle Delamore Partners",
  "Pbtech Limited" = "Pb Tech",
  "Pb Technologies" = "Pb Tech",
  "Pb Technologies Ltd" = "Pb Tech",
  "Pictor Ltd" = "Pictor Limited",
  "Pipers Intellectual Property" = "Pipers Ip",
  "Polymer Group Ltd." = "Polymer Group Ltd",
  "Poweron Ltd" = "Poweron",
  "Ppg Industries New Zealand Limited" = "Ppg Industries",
  "Prescott Engineering (2015) Ltd." = "Prescott Engineering",
  "Prescott Engineering Ltd." = "Prescott Engineering",
  "Pricewaterhousecoopers Australia" = "Pricewaterhousecoopers",
  "Primech Ltd" = "Primech",
  "Ptm Consultants Ltd" = "Ptm Consultants",
  "Pushpay Holdings Limited" = "Pushpay",
  "Pwc New Zealand" = "Pwc",
  
  "Qm Development Limited" = "Qm Development Ltd",
  "Qrious" = "Qrious Limited",
  "Quantifi Photonics" = "Quantifi Photonics Ltd",
  "Quantifi Photonics Ltd." = "Quantifi Photonics Ltd",
  "Quantifi Photonics Limited" = "Quantifi Photonics Ltd",
  "Quantiful Ltd." = "Quantiful",
  "Quantiful Limited" = "Quantiful",
  "Quickcircuit" = "Quick Circuit",
  "Rakon Limited" = "Rakon",
  "Rakon Nz Ltd" = "Rakon",
  "Redwood Engineering Limited" = "Redwood Engineering",
  "Resource Development Consultants Limited (rdcl)" = "Resource Development Consultants Ltd.",
  "Rheem New Zealand Limited" = "Rheem",
  "Rheem New Zealand Ltd" = "Rheem",
  "Richards Consulting Engineers" = "Richards Consulting",
  "Riley Consultants Ltd." = "Riley Consultants Ltd",
  "Riley Consultants" = "Riley Consultants Ltd",
  "Rinnai New Zealand" = "Rinnai Nz",
  "Rinnai Nz Ltd" = "Rinnai Nz",
  "Rinnai New Zealand Limited" = "Rinnai Nz",
  "Rinnai Nz, 105 Pavilion Drive" = "Rinnai Nz",
  "Risosenterprises Ltd." = "Risosenterprises Ltd",
  "Risosenterprises" = "Risosenterprises Ltd",
  "Risosenterprises","Robinson Research Institute - Victoria University Of Wellington" = "Robinson Research Institute",
  "Robotics Plus Limited" = "Robotics Plus Ltd",
  
  "Robotics Plus" = "Robotics Plus Ltd",
  "Robotics Plus Inc" = "Robotics Plus Ltd",
  "Rocket Lab Ltd." = "Rocket Lab",
  "Rocketlab" = "Rocket Lab",
  "Rocos Global Limited" = "Rocos",
  "Ross Reid Contractors Ltd" = "Ross Reids Contractors",
  "Ross Reid Contractors Limited" = "Ross Reids Contractors",
  "Royal New Zealand Air Force" = "Royal New Zealand Navy",
  "Ryman Healthcare Ltd" = "Ryman Healthcare",
  "Ryman Health Care" = "Ryman Healthcare",
  "Ryman" = "Ryman Healthcare",
  "Safety Solutions Limited" = "Safety Solutions Ltd",
  "Sailgp" = "Sail Gp",
  "Sail Gp Technologies" = "Sail Gp",
  "Sandfield Associates Limited" = "Sandfield",
  "Sandfield Associates" = "Sandfield",
  "Sap New Zealand Ltd" = "Sap",
  "Schneuder Electric" = "Schneider Electric",
  "Scion" = "Scion Research",
  "Scratchpad" = "Scratchpad Ltd",
  "Scratchpad Stonefields" = "Scratchpad Ltd",
  "Seadragon Marine Oils Limited" = "Seadragon",
  "Sealegs International Limited" = "Sealegs",
  "Sealegs International Ltd" = "Sealegs",
  "Serato Ltd" = "Serato Limited",
  "Serko" = "Serko Ltd",
  "Serko Limited" = "Serko Ltd",
  "Serko Ltd." = "Serko Ltd",
  "Sharpeye Limited" = "Dempsey Wood",
  "Sharpeye" = "Dempsey Wood",
  "Siemens Mobility New Zealand" = "Siemens",
  "Silvester Clark Ltd." = "Silvester Clark",
  "Simpson Shaw Surveyors" = "Simpson Shaw",
  "Sistema Plastics" = "Sistema Plastics Limited",
  "Skinnyspark New Zealand" = "Skinny  Spark New Zealand",
  "Smart City Streets" = "Smart City Streets Ltd",
  "Smx Email" = "Smx",
  "Soletanche Bachy - Link Alliance" = "Soletanche Bachy International",
  "Southbase Construction Ltd" = "Southbase Construction",
  "Space Structural Consultants" = "Space Structural Consultants Ltd",
  "Spark 64 Ltd." = "Spark 64",
  "Spark Nz Ltd" = "Spark Nz",
  "Spark New Zealand" = "Spark Nz",
  "Spark Nz Trading" = "Spark Nz",
  "Spark New Zealand - Skinny" = "Spark Nz",
  "Spark New Zealand Trading" = "Spark Nz",
  "Spencer Holmes Limited" = "Spencer Holmes",
  "Stantec New Zealand" = "Stantec",
  "Stellar Projects" = "Stellar Projects Ltd",
  "Stellar Projects Limited" = "Stellar Projects Ltd",
  "Stratum Consultants Limited" = "Stratum Consultants",
  "Suez Smart Solutions Ltd" = "Suez Smart Solutions",
  "Suez Smart Solutions Nz" = "Suez Smart Solutions",
  "Suez Smart Solutions Limited" = "Suez Smart Solutions",
  "Summer Research Scholarship At University Of Auckland" = "Summer Research Scholarship",
  "Summer Research Scholarship - How Crime Against Women Deters Economic Growth Theory Meets Data" = "Summer Research Scholarship",
  "Susquhanna International Group (sig)" = "Susquehanna International Group",
  "Swages" = "Swages Engineering",
  "Swages Engineering Limited"= "Swages Engineering",
  "Synlait Milk Auckland" = "Synlait",
  "Syrp" = "Syrp Lab",
  "Talegent Limited Partnership" = "Talegent",
  "Tasman Engineering Company Ltd." = "Tasman Engineering",
  "Tasman Insulation New Zealand Limited" = "Tasman Insulation Nz Limited",
  "Tasti Products Limited" = "Tasti Products Ltd",
  "Tasti Products" = "Tasti Products Ltd",
  "Tci New Zealand 1995 Ltd" = "Tci",
  "Temperzone Limited" = "Temperzone",
  "Ten4 Transport Engineering" = "Ten4 Engineering",
  "Thales Group - Gtsnz" = "Thales Nz",
  "The Auckland Bioengineering Institute" = "The University Of Auckland",
  "The Fletcher Construction Company" = "Fletcher Construction",
  "The Griffin#s Food Company" = "The Griffins Food Company",
  "The Labour Exchange Limited" = "The Labour Exchange",
  "The Labour Exchange Ltd" = "The Labour Exchange",
  "The Labour Exchange Ltd." = "The Labour Exchange",
  "The Roofing Store (ks Holdings)" = "The Roofing Store",
  "The Roofing Store Ltd - Ks Holdings Ltd" = "The Roofing Store",
  "The University Of Auckland Summer Research Scholarship" = "The University Of Auckland",
  "The University Of Auckland-department Of Chemical And Material Engineering" = "The University Of Auckland",
  "The University Of Auckland, Summer Research" = "The University Of Auckland",
  "The University Of Auckland, Digital Services," = "The University Of Auckland",
  "The University Of Auckland Faculty Of Engineering" = "The University Of Auckland",
  "The University Of Auckland - Learning Environment Support Unit"= "The University Of Auckland",
  "The University Of Auckland Engineering Department" = "The University Of Auckland",
  "The University Of Auckland - Summer Research Scholarship" = "The University Of Auckland",
  "The University Of Auckland - Faculty Of Engineering"= "The University Of Auckland",
  "The University Of Auckland - Faculty Of Medical And Health Sciences" = "The University Of Auckland",
  "The University Of Auckland, Faculty Of Engineering" = "The University Of Auckland",
  "The University Of Auckland School Of Environment" = "The University Of Auckland",
  "The University Of Auckland Department Of Physics" = "The University Of Auckland",
  "The University Of Auckland Waste  Resource Recovery Research Group" = "The University Of Auckland",
  "The University Of Auckland (faculty Of Engineering)" = "The University Of Auckland",
  "The University Of Auckland - School Of Computer Science" = "The University Of Auckland",
  "The University Of Auckland - Faculty Of Business And Economics" = "The University Of Auckland",
  "The University Of Auckland - Department Of Chemical And Materials Engineering" = "The University Of Auckland",
  "The University Of Auckland - Chemical  Materials Department" = "The University Of Auckland",
  
  "Thermosash Commerical Ltd" = "Thermosash Commercial Limited",
  "Thl Design Group Limited" = "Thl Design Group",
  "Thl Design Group Ltd" = "Thl Design Group",
  "Tidy International Limited" = "Tidy International",
  "Tidy International (nz) Ltd" = "Tidy International",
  "Tilsley Engineering Ltd." = "Tilsley Engineering Ltd",
  "Tilsley Engineering Limited" = "Tilsley Engineering Ltd",
  "Tim Solution Ltd." = "Tim Solution Ltd",
  "Timi Construction Limited" = "Timi Construction Ltd",
  "Tip Top Ice Cream Company" = "Tip Top Ice Cream Ltd.",
  "Toki Recruitment Ltd  Fulton Hogan" = "Toki Recruitment Ltd",
  "Toki Recruitment Limited" = "Toki Recruitment Ltd",
  "Tomra" = "Tomra Fresh Food",
  "Tomra Food" = "Tomra Compac",
  "Tomra Fresh Food  Compac" = "Tomra Compac",
  "Tonkin  Taylor Ltd" = "Tonkin  Taylor",
  "Tonkin And Taylor" = "Tonkin  Taylor",
  "Tonkin And Taylor Limited" = "Tonkin  Taylor",
  "Top Energy Limited" = "Top Energy",
  "Toptec Construction Ltd" = "Toptec Construction Limited",
  "Trade Me Ltd." = "Trade Me",
  "Traffic Engineering Solutions Ltd" = "Traffic Engineering Solutions",
  "Traffic Engineering Solutions Limited" = "Traffic Engineering Solutions",
  "Traffic Engineering Solution" = "Traffic Engineering Solutions",
  "Transpower New Zealand" = "Transpower",
  "Transpower New Zealand Ltd" = "Transpower",
  "Transpower New Zealand Limited" = "Transpower",

  "Trimble Navigation New Zealand Limited", "Trimble Navigation New Zealand Ltd",
  "Trimble, Inc.",
  "Trimble Navigation New Zealand Limited" = "Trimble Inc.",
  "Trimble Navigation New Zealand Ltd" = "Trimble Inc.",
  "Trimble, Inc." = "Trimble Inc.",
 
  
  "Unison Networks Limited" = "Unison",
  "University Of Auckland, Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland Engineering Science Department" = "The University Of Auckland",
  "University Of Auckland Ecse" = "The University Of Auckland",
  "University Of Auckland - Summer Research Scholarship" = "The University Of Auckland",
  "University Of Auckland Power Electronics Laboratory" = "The University Of Auckland",
  "University Of Auckland - Faculty Of Medical Health Sciences" = "The University Of Auckland",
  "University Of Auckland (summer Research Scholarship)" = "The University Of Auckland",
  "University Of Auckland (summer Research Scholarship)" = "The University Of Auckland",
  "University Of Auckland - Department Of Civil And Environmental Engineering" ="The University Of Auckland",
  "University Of Auckland, Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland Summer Research Scholarships" = "The University Of Auckland",
  "University Of Auckland, Department Of Exercise Sciences" = "The University Of Auckland",
  "University Of Auckland, Department Of Electrical, Computer And Software Engineering" = "The University Of Auckland",
  "University Of Auckland Department Of Civil And Environmental Engineering" = "The University Of Auckland",
  "University Of Auckland - Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland (property Services Team)" = "The University Of Auckland",
  "University Of Auckland - Department Of Chemical And Materials Engineering" = "The University Of Auckland",
  "University Of Auckland Cacm" = "The University Of Auckland",
  "University Of Auckland Faculty Of Medical And Health Sciences" = "The University Of Auckland",
  "University Of Auckland - Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland Faculty Of Medical And Health Sciences" = "The University Of Auckland",
  "University Of Auckland Formula Sae Team Inc." ="The University Of Auckland",
  "University Of Auckland Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland, Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland Department Of Engineering Science" = "The University Of Auckland",
  "University Of Auckland (auckland Space Insitute)" = "The University Of Auckland",
  "University Of Auckland - Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland, Robotics Research Group" = "The University Of Auckland",
  "University Of Auckland Faculty Of Engineering" = "The University Of Auckland",
  "University Of Auckland - Digital Services" = "The University Of Auckland",
  "University Of Auckland - Department Of Civil And Environmental Engineering" = "The University Of Auckland",
  "University Of Auckland - Department Of Engineering Science" = "The University Of Auckland",
  "University Of Auckland Department Of Mathematics" = "The University Of Auckland",
  "University Of Auckland Faculty Of Civil And Environmental Engineering" = "The University Of Auckland",
  "University Of Auckland Bioengineering Institute" = "The University Of Auckland",
  "University Of Auckland, Newmarket Campus" = "The University Of Auckland",
  
  
  "Unova Control Ltd" = "Unova Control",
  "Dempsey Wood Civil" = "The University Of Auckland",
  "Dempsey Wood Civil" = "The University Of Auckland",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "The University Of Auckland",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  "Dempsey Wood Civil" = "Dempsey Wood",
  
)

change_df = valid_df
change_df$Company.Name = ifelse(
  change_df$Company.Name %in% needsChange,
  change[change_df$Company.Name],
  change_df$Company.Name 
)

final_df = change_df

write.csv(final_df, "cleaned.csv")
